services:
  sonar-backend:
    container_name: sonar-backend
    build: ./backend/
    image: "louisross/sonar-backend:1.1"
    ports:
      - 5000:5000
    volumes:
      - "./configuration/:/configuration"
      - "/mnt/m2/sonar/:/sonar"
    depends_on:
  sonar-portal:
    container_name: sonar-portal
    build: "./portal"
    image: "louisross/portal:1.1"
    ports:
      - 8080:3000
    volumes:
      - "./configuration/:/configuration"
    depends_on:
      - sonar-backend
